### ISSUE TITLE
Segmentation fault using Kodi on rkl

### ISSUE THREAD

**Issue by bkuhls** [intel/media-driver#1209]
Hi,,

11th Gen Intel(R) Core(TM) i9-11900T
00:02.0 VGA compatible controller: Intel Corporation Device 4c8a (rev 04)
libdrm-2.4.106
libva-1.12.0
gmmlib-21.1.3
mesa3d-21.1.3
kernel 5.13-rc6 from current drm-tip tree https://cgit.freedesktop.org/drm-tip/tree/?id=3c00434f0d7ff138a7b56d5a901586d4473e10a7

using media-driver tree https://github.com/intel/media-driver/commits/08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7 Kodi segfaults during startup:
```
(gdb) bt full
#0  MosUtilities::MosDeleteUtil<MhwCpInterface*> (ptr=<synthetic pointer>)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_softlet/agnostic/common/os/mos_utilities_next.h:132
No locals.
#1  MOS_DeleteUtil<MhwCpInterface*> (ptr=<synthetic pointer>)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/agnostic/common/os/mos_utilities.h:223
No locals.
#2  Delete_MhwCpInterface (pInterface=0x242b410)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/linux/common/cp/hw/mhw_cp_interface.cpp:54
        cp_interface = <optimized out>
#3  0x00007fffe39dd0b5 in MhwInterfaces::Destroy (this=0x242b460)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/linux/common/media_interfaces/media_interfaces.cpp:206
No locals.
#4  0x00007fffe39dd2a6 in MhwInterfaces::Destroy (this=this@entry=0x242b460)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/linux/common/media_interfaces/media_interfaces.cpp:218
No locals.
#5  0x00007fffe3a4c4b1 in MhwInterfacesG12Tgllp::Destroy (this=0x242b460)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/media_interface/media_interfaces_m12_tgllp/media_interfaces_g12_tgllp.cpp:328
No locals.
#6  0x00007fffe39de5ed in MmdDevice::CreateFactory (osDriverContext=<optimized out>)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/linux/common/media_interfaces/media_interfaces.cpp:380
        osInterface = 0x2412390
        device = 0x242b3f0
        mhwInterfaces = 0x242b460
        platform = {eProductFamily = IGFX_ROCKETLAKE, ePCHProductFamily = PCH_UNKNOWN, eDisplayCoreFamily = IGFX_GEN12_CORE,
          eRenderCoreFamily = IGFX_GEN12_CORE, ePlatformType = PLATFORM_MOBILE, usDeviceID = 19594, usRevId = 4,
          usDeviceID_PCH = 0, usRevId_PCH = 0, eGTType = GTTYPE_GT1}
        mmdDevice = <optimized out>
#7  0x00007fffe3a2693e in MosDecompression::MosDecompression (this=0x23e7670, osDriverContext=<optimized out>)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/media_driver_next/linux/common/os/mos_decompression.cpp:36
No locals.
#8  0x00007fffe3a1b8a4 in MosUtilities::MosNewUtil<MosDecompression, _MOS_OS_CONTEXT*&> ()
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_softlet/agnostic/common/os/mos_utilities_next.h:77
        ptr = <optimized out>
#9  MOS_NewUtil<MosDecompression, _MOS_OS_CONTEXT*&> ()
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/agnostic/common/os/mos_utilities.h:179
No locals.
#10 OsContextSpecificNext::Init (this=0x23a9e20, ddiDriverContext=0x7fffffff77e0)
    at /home/fli4l/.fbr/buildroot/output/build/intel-mediadriver-08cbe4c102d1fe8ba1f5b699b1a0c1c831aef8f7/media_driver/media_driver_next/linux/common/os/mos_context_specific_next.cpp:226
        gmmFuncs = {pfnCreateSingletonContext = 0x7fffe33014e0, pfnDestroySingletonContext = 0x7fffe3301c00,
          pfnCreateClientContext = 0x7fffe330e640, pfnDeleteClientContext = 0x7fffe330e690}
        gmmStatus = <optimized out>
        gmmSkuTable = {{FtrULT = 0, FtrVERing = 1, FtrVcs2 = 0, FtrLCIA = 0, FtrCCSRing = 0, FtrCCSNode = 0, FtrTileY = 1,
            FtrCCSMultiInstance = 0}, {FtrPPGTT = 1, FtrIA32eGfxPTEs = 1, FtrMemTypeMocsDeferPAT = 0, FtrPml4Support = 0,
            FtrSVM = 0, FtrTileMappedResource = 0, FtrTranslationTable = 0, FtrUserModeTranslationTable = 0, FtrNullPages = 0,
            FtrEDram = 0, FtrLLCBypass = 0, FtrCrystalwell = 0, FtrCentralCachePolicy = 0, FtrWddm2GpuMmu = 0,
            FtrWddm2Svm = 0, FtrStandardMipTailFormat = 0, FtrWddm2_1_64kbPages = 0, FtrE2ECompression = 1, FtrLinearCCS = 1,
            FtrFrameBufferLLC = 0, FtrDriverFLR = 0, FtrLocalMemory = 0, FtrCameraCaptureCaching = 0,
            FtrLocalMemoryAllows4KB = 0, FtrPpgtt64KBWalkOptimization = 0, FtrFlatPhysCCS = 0, FtrDisplayXTiling = 0,
            FtrMultiTileArch = 0}, {FtrAstcLdr2D = 0, FtrAstcHdr2D = 0, FtrAstc3D = 0}, {FtrFbc = 0}, {FtrRendComp = 0,
            FtrDisplayYTiling = 1, FtrDisplayDisabled = 0}, {FtrS3D = 0, FtrDisplayEngineS3d = 0}, {FtrVgt = 0}, {
            FtrAssignedGpuTile = 0}}
        gmmWaTable = {WaAlignIndexBuffer = 0, WaValign2ForR8G8B8UINTFormat = 0, WaValign2For96bppFormats = 0, WaCursor16K = 0,
          Wa8kAlignforAsyncFlip = 0, Wa29BitDisplayAddrLimit = 0, WaAlignContextImage = 0, WaForceGlobalGTT = 0,
          WaReportPerfCountForceGlobalGTT = 0, WaOaAddressTranslation = 0, Wa2RowVerticalAlignment = 0,
          WaPpgttAliasGlobalGttSpace = 0, WaClearFenceRegistersAtDriverInit = 0, WaRestrictPitch128KB = 0, WaAvoidLLC = 0,
          WaAvoidL3 = 0, Wa16TileFencesOnly = 0, Wa16MBOABufferAlignment = 0, WaTranslationTableUnavailable = 0,
          WaNoMinimizedTrivialSurfacePadding = 0, WaNoBufferSamplerPadding = 0, WaSurfaceStatePlanarYOffsetAlignBy2 = 0,
          WaGttCachingOffByDefault = 0, WaTouchAllSvmMemory = 0, WaIOBAddressMustBeValidInHwContext = 0,
          WaFlushTlbAfterCpuGgttWrites = 0, WaMsaa8xTileYDepthPitchAlignment = 0, WaDisableNullPageAsDummy = 0,
          WaUseVAlign16OnTileXYBpp816 = 0, WaNoMocsEllcOnly = 0, WaGttPat0 = 0, WaGttPat0WB = 0,
          WaMemTypeIsMaxOfPatAndMocs = 0, WaGttPat0GttWbOverOsIommuEllcOnly = 0, WaAddDummyPageForDisplayPrefetch = 0,
          WaLLCCachingUnsupported = 0, WaEncryptedEdramOnlyPartials = 0, WaDisableEdramForDisplayRT = 0,
          WaAstcCorruptionForOddCompressedBlockSizeX = 0, WaLosslessCompressionSurfaceStride = 0,
          Wa4kAlignUVOffsetNV12LinearSurface = 1, WaFbcLinearSurfaceStride = 0, WaDoubleFastClearWidthAlignment = 0,
          WaCompressedResourceRequiresConstVA21 = 0, WaDisregardPlatformChecks = 1, WaAlignYUVResourceToLCU = 1,
          Wa32bppTileY2DColorNoHAlign4 = 0, WaAuxTable16KGranular = 0, WaLimit128BMediaCompr = 0,
          WaUntypedBufferCompression = 0, WaDefaultTile4 = 0}
        gmmGtInfo = {EUCount = 0, ThreadCount = 0, SliceCount = 0, SubSliceCount = 0, DualSubSliceCount = 0,
          L3CacheSizeInKb = 0, LLCCacheSizeInKb = 0, EdramSizeInKb = 0, L3BankCount = 0, MaxFillRate = 0,
          EuCountPerPoolMax = 0, EuCountPerPoolMin = 0, TotalVsThreads = 0, TotalHsThreads = 0, TotalDsThreads = 0,
          TotalGsThreads = 0, TotalPsThreadsWindowerRange = 0, TotalVsThreads_Pocs = 0, CsrSizeInMb = 0, MaxEuPerSubSlice = 0,
          MaxSlicesSupported = 0, MaxSubSlicesSupported = 0, MaxDualSubSlicesSupported = 0, IsL3HashModeEnabled = false,
          VDBoxInfo = {Instances = {Bits = {VDBox0Enabled = 0, VDBox1Enabled = 0, VDBox2Enabled = 0, VDBox3Enabled = 0,
                VDBox4Enabled = 0, VDBox5Enabled = 0, VDBox6Enabled = 0, VDBox7Enabled = 0, Reserved = 0},
              VDBoxEnableMask = 0}, SFCSupport = {SfcSupportedBits = {VDBox0 = 0, VDBox1 = 0, VDBox2 = 0, VDBox3 = 0,
                VDBox4 = 0, VDBox5 = 0, VDBox6 = 0, VDBox7 = 0, Reserved = 0}, Value = 0}, NumberOfVDBoxEnabled = 0,
            IsValid = true}, VEBoxInfo = {Instances = {Bits = {VEBox0Enabled = 1, VEBox1Enabled = 0, VEBox2Enabled = 0,
                VEBox3Enabled = 0, Reserved = 0}, VEBoxEnableMask = 1}, SFCSupport = {SfcSupportedBits = {VEBox0 = 0,
                VEBox1 = 0, VEBox2 = 0, VEBox3 = 0, Reserved = 0}, Value = 0}, NumberOfVEBoxEnabled = 0, IsValid = true},
          SliceInfo = {{Enabled = false, SubSliceInfo = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {
                  Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                  EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false,
                  EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {
                  Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                  EuEnabledMask = 0}}, DSSInfo = {{Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}}, SubSliceEnabledCount = 0, DualSubSliceEnabledCount = 0}, {Enabled = false,
              SubSliceInfo = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                  EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false,
                  EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {
                  Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                  EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}, DSSInfo = {{Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}},
              SubSliceEnabledCount = 0, DualSubSliceEnabledCount = 0}, {Enabled = false, SubSliceInfo = {{Enabled = false,
                  EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {
                  Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                  EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false,
                  EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {
                  Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}, DSSInfo = {{Enabled = false, SubSlice = {{
                      Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}},
              SubSliceEnabledCount = 0, DualSubSliceEnabledCount = 0}, {Enabled = false, SubSliceInfo = {{Enabled = false,
                  EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {
                  Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                  EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false,
                  EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {
                  Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}, DSSInfo = {{Enabled = false, SubSlice = {{
                      Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}, {Enabled = false,
                  SubSlice = {{Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}}}, {Enabled = false, SubSlice = {{Enabled = false, EuEnabledCount = 0,
                      EuEnabledMask = 0}, {Enabled = false, EuEnabledCount = 0, EuEnabledMask = 0}}}},
              SubSliceEnabledCount = 0, DualSubSliceEnabledCount = 0}}, IsDynamicallyPopulated = false, SqidiInfo = {
            NumberofSQIDI = 0, NumberofDoorbellPerSQIDI = 0}, ReservedCCSWays = 0, CCSInfo = {Instances = {Bits = {
                CCS0Enabled = 0, CCS1Enabled = 0, CCS2Enabled = 0, CCS3Enabled = 0, Reserved = 0}, CCSEnableMask = 0},
            NumberOfCCSEnabled = 0, IsValid = false}, MultiTileArchInfo = {TileCount = 0 '\000', {{Tile0 = 0 '\000',
                Tile1 = 0 '\000', Tile2 = 0 '\000', Tile3 = 0 '\000', Reserved = 0 '\000'}, TileMask = 0 '\000'},
            IsValid = false}, NumThreadsPerEu = 0, CacheTypes = {{L3 = 0, LLC = 0, eDRAM = 0, Reserved = 0},
            CacheTypeMask = 0}, MaxVECS = 0}
        eStatus = <optimized out>
        UserFeatureData = {{bData = 0, u32Data = 0, u64Data = 0, i32Data = 0, i64Data = 0, fData = 0, StringData = {
              pStringData = 0x0, uMaxSize = 0, uSize = 0}, MultiStringData = {pMultStringData = 0x0, uMaxSize = 0, uSize = 0,
              pStrings = 0x0, uCount = 0}, BinaryData = {pBinaryData = 0x0, uMaxSize = 0, uSize = 0}}, i32DataFlag = 0}
        osDriverContext = 0x7fffffff77e0
        iDeviceId = <optimized out>
```

**Comment by bkuhls** [comment]
Vanilla kernel 5.13-rc6 does not cause segfaults, so the problem seems to be caused by patches from drm-tip
