### ISSUE TITLE
mpeg2 encode may lead to memory overrun

### ISSUE THREAD

**Issue by Alexandr-Konovalov** [intel/media-driver#720]
After check `m_currentNumPatchLocations >= m_maxPatchLocationsize` was added  to [GpuContextSpecific::SetPatchEntry()](https://github.com/intel/media-driver/blob/18e2b9fb4ad94c385f0cf37e6e10ae866e80da11/media_driver/linux/common/os/mos_gpucontext_specific.cpp#L374), it triggers with stack below 

[libva calls before the memory overrun](https://github.com/intel/media-driver/files/3568654/libva.log.083455.thd-0x000005aa.log)

```
#2  0x00007ffff45cf3eb in GpuContextSpecific::SetPatchEntry (this=0x14725e0, osInterface=0x13e11d0, params=0x7ffff06a6800) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/linux/common/os/mos_gpucontext_specific.cpp:378
#3  0x00007ffff45be1ce in Mos_Specific_SetPatchEntry (pOsInterface=0x13e11d0, pParams=0x7ffff06a6800) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/linux/common/os/mos_os_specific.c:3074
#4  0x00007ffff3ff2258 in Mhw_AddResourceToCmd_PatchList (pOsInterface=0x13e11d0, pCmdBuffer=0x7ffff06a6c40, pParams=0x7ffff06a6890) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/agnostic/common/hw/mhw_utilities.c:229
#5  0x00007ffff417bbb5 in MhwMiInterfaceG9::AddMiBatchBufferStartCmd (this=0x13f54b0, cmdBuffer=0x7ffff06a6c40, batchBuffer=0x7ffff06a6930) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/agnostic/gen9/hw/mhw_mi_g9_X.cpp:76
#6  0x00007ffff3fc3f35 in CodechalEncodeMpeg2::SendSliceParams (this=0x13f82a0, cmdBuffer=0x7ffff06a6c40, params=0x7ffff06a6bc0) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/agnostic/common/codec/hal/codechal_encode_mpeg2.cpp:4548
#7  0x00007ffff3fc47bb in CodechalEncodeMpeg2::ExecuteSliceLevel (this=0x13f82a0) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/agnostic/common/codec/hal/codechal_encode_mpeg2.cpp:4630
#8  0x00007ffff3ea9ba8 in CodechalEncoderState::ExecuteEnc (this=0x13f82a0, encodeParams=0x7ffff06a7c70) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp:4442
#9  0x00007ffff3e986f4 in CodechalEncoderState::Execute (this=0x13f82a0, params=0x7ffff06a7c70) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp:587
#10 0x00007ffff45578d8 in DdiEncodeMpeg2::EncodeInCodecHal (this=0x13d1980, numSlices=18) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/linux/common/codec/ddi/media_ddi_encode_mpeg2.cpp:359
#11 0x00007ffff45094bf in DdiEncodeBase::EndPicture (this=0x13d1980, ctx=0x1361460, context=536870912) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/linux/common/codec/ddi/media_ddi_encode_base.cpp:77
#12 0x00007ffff4514741 in DdiEncode_EndPicture (ctx=0x1361460, context=536870912) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/linux/common/codec/ddi/media_libva_encoder.cpp:599
#13 0x00007ffff457bf25 in DdiMedia_EndPicture (ctx=0x1361460, context=536870912) at /home/akonovx/src/Intel-media-driver/media-driver/media_driver/linux/common/ddi/media_libva.cpp:3357
#14 0x00007ffff653ee5f in vaEndPicture (dpy=0x13612f0, context=536870912) at va.c:1583
#15 0x00007ffff121c06f in MfxHwMpeg2Encode::VAAPIEncoder::Execute (this=0x13d0270, pExecuteBuffers=0x13c9c60, funcId=258, pUserData=0x0, userDataLen=0) at /home/akonovx/mfx_home/mdp_msdk-lib/_studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp:1362
#16 0x00007ffff121c58a in MfxHwMpeg2Encode::VAAPIEncoder::Execute (this=0x13d0270, pExecuteBuffers=0x13c9c60, pUserData=0x0, userDataLen=0) at /home/akonovx/mfx_home/mdp_msdk-lib/_studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp:1471
#17 0x00007ffff11aeab4 in MPEG2EncoderHW::MFXVideoENCODEMPEG2_HW_DDI::SubmitFrame (this=0x13c9c30, pParams=0x13c0364, pFrames=0x13c03b0, pUserData=0x0, userDataLen=0, qp=0 '\000', mbqp=0x0, numMB=0) at /home/akonovx/mfx_home/mdp_msdk-lib/_studio/mfx_lib/encode_hw/mpeg2/include/mfx_mpeg2_encode_full_hw.h:242
#18 0x00007ffff11ae7ec in MPEG2EncoderHW::MFXVideoENCODEMPEG2_HW_DDI::SubmitFrame (this=0x13c9c30, pIntTask=0x13c0360, pUserData=0x0, userDataLen=0, qp=0 '\000') at /home/akonovx/mfx_home/mdp_msdk-lib/_studio/mfx_lib/encode_hw/mpeg2/include/mfx_mpeg2_encode_full_hw.h:159
#19 0x00007ffff11acc2f in MPEG2EncoderHW::FullEncode::SubmitFrame (this=0x13bf790, pExtTask=0x1491418) at /home/akonovx/mfx_home/mdp_msdk-lib/_studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_full_hw.cpp:477
```

Related Valgrind report
```
==3316== Invalid read of size 4
==3316==    at 0x8CCD8DF: GpuContextSpecific::SubmitCommandBuffer(_MOS_INTERFACE*, _MOS_COMMAND_BUFFER*, bool) (mos_gpucontext_specific.cpp:709)
==3316==    by 0x8CBD564: Mos_Specific_SubmitCommandBuffer(_MOS_INTERFACE*, _MOS_COMMAND_BUFFER*, int) (mos_os_specific.c:3843)
==3316==    by 0x85A4939: CodechalEncoderState::SubmitCommandBuffer(_MOS_COMMAND_BUFFER*, int) (codechal_encoder_base.cpp:4097)
==3316==    by 0x86C1F68: CodechalEncodeMpeg2::ExecuteSliceLevel() (codechal_encode_mpeg2.cpp:4716)
==3316==    by 0x85A6BA7: CodechalEncoderState::ExecuteEnc(EncoderParams*) (codechal_encoder_base.cpp:4442)
==3316==    by 0x85956F3: CodechalEncoderState::Execute(void*) (codechal_encoder_base.cpp:587)
==3316==    by 0x8C548D7: DdiEncodeMpeg2::EncodeInCodecHal(unsigned int) (media_ddi_encode_mpeg2.cpp:359)
==3316==    by 0x8C064BE: DdiEncodeBase::EndPicture(VADriverContext*, unsigned int) (media_ddi_encode_base.cpp:77)
==3316==    by 0x8C11740: DdiEncode_EndPicture(VADriverContext*, unsigned int) (media_libva_encoder.cpp:599)
==3316==    by 0x8C78F24: DdiMedia_EndPicture(VADriverContext*, unsigned int) (media_libva.cpp:3357)
==3316==    by 0x7CB9E5E: vaEndPicture (va.c:1583)
==3316==    by 0xC3DB06E: MfxHwMpeg2Encode::VAAPIEncoder::Execute(MfxHwMpeg2Encode::ExecuteBuffers*, unsigned int, unsigned char*, unsigned int) (mfx_mpeg2_encode_vaapi.cpp:1362)
==3316==    by 0xC3DB589: MfxHwMpeg2Encode::VAAPIEncoder::Execute(MfxHwMpeg2Encode::ExecuteBuffers*, unsigned char*, unsigned int) (mfx_mpeg2_encode_vaapi.cpp:1471)
==3316==    by 0xC36DAB3: MPEG2EncoderHW::MFXVideoENCODEMPEG2_HW_DDI::SubmitFrame(mfxFrameParamMPEG2*, MPEG2EncoderHW::FramesSet*, unsigned char*, unsigned int, unsigned char, unsigned char*, unsigned int) (mfx_mpeg2_encode_full_hw.h:242)
==3316==    by 0xC36D7EB: MPEG2EncoderHW::MFXVideoENCODEMPEG2_HW_DDI::SubmitFrame(MPEG2EncoderHW::EncodeFrameTask*, unsigned char*, unsigned int, unsigned char) (mfx_mpeg2_encode_full_hw.h:159)
==3316==    by 0xC36BC2E: MPEG2EncoderHW::FullEncode::SubmitFrame(sExtTask2*) (mfx_mpeg2_encode_full_hw.cpp:477)
==3316==    by 0xC36BF7E: TaskRoutineSubmit(void*, void*, unsigned int, unsigned int) (mfx_mpeg2_encode_full_hw.cpp:544)
==3316==    by 0xC0A65CA: mfxSchedulerCore::call_pRoutine(MFX_CALL_INFO&) (mfx_scheduler_core.h:531)
==3316==    by 0xC0A624C: mfxSchedulerCore::ThreadProc(MFX_SCHEDULER_THREAD_CONTEXT*) (mfx_scheduler_core_thread.cpp:124)
==3316==    by 0xC09EB6B: mfxSchedulerCore::Initialize2(MFX_SCHEDULER_PARAM2 const*)::{lambda()#1}::operator()() const (mfx_scheduler_core_ischeduler.cpp:201)
==3316==  Address 0xb2ced90 is 0 bytes after a block of size 3,552 alloc'd
==3316==    at 0x4C2BB58: realloc (vg_replace_malloc.c:785)
==3316==    by 0x8CCD156: GpuContextSpecific::ResizeCommandBufferAndPatchList(unsigned int, unsigned int, unsigned int) (mos_gpucontext_specific.cpp:593)
==3316==    by 0x8CBE757: Mos_Specific_ResizeCommandBufferAndPatchList (mos_os_specific.c:4244)
==3316==    by 0x84AB026: CodechalHwInterface::ResizeCommandBufferAndPatchListOs(unsigned int, unsigned int) (codechal_hw.cpp:657)
==3316==    by 0x84AAD1F: CodechalHwInterface::ResizeCommandBufferAndPatchList(unsigned int, unsigned int) (codechal_hw.cpp:627)
==3316==    by 0x859C45A: CodechalEncoderState::VerifySpaceAvailable() (codechal_encoder_base.cpp:2292)
==3316==    by 0x85A6A9E: CodechalEncoderState::ExecuteEnc(EncoderParams*) (codechal_encoder_base.cpp:4435)
==3316==    by 0x85956F3: CodechalEncoderState::Execute(void*) (codechal_encoder_base.cpp:587)
==3316==    by 0x8C548D7: DdiEncodeMpeg2::EncodeInCodecHal(unsigned int) (media_ddi_encode_mpeg2.cpp:359)
==3316==    by 0x8C064BE: DdiEncodeBase::EndPicture(VADriverContext*, unsigned int) (media_ddi_encode_base.cpp:77)
==3316==    by 0x8C11740: DdiEncode_EndPicture(VADriverContext*, unsigned int) (media_libva_encoder.cpp:599)
==3316==    by 0x8C78F24: DdiMedia_EndPicture(VADriverContext*, unsigned int) (media_libva.cpp:3357)
==3316==    by 0x7CB9E5E: vaEndPicture (va.c:1583)
==3316==    by 0xC3DB06E: MfxHwMpeg2Encode::VAAPIEncoder::Execute(MfxHwMpeg2Encode::ExecuteBuffers*, unsigned int, unsigned char*, unsigned int) (mfx_mpeg2_encode_vaapi.cpp:1362)
==3316==    by 0xC3DB589: MfxHwMpeg2Encode::VAAPIEncoder::Execute(MfxHwMpeg2Encode::ExecuteBuffers*, unsigned char*, unsigned int) (mfx_mpeg2_encode_vaapi.cpp:1471)
==3316==    by 0xC36DAB3: MPEG2EncoderHW::MFXVideoENCODEMPEG2_HW_DDI::SubmitFrame(mfxFrameParamMPEG2*, MPEG2EncoderHW::FramesSet*, unsigned char*, unsigned int, unsigned char, unsigned char*, unsigned int) (mfx_mpeg2_encode_full_hw.h:242)
==3316==    by 0xC36D7EB: MPEG2EncoderHW::MFXVideoENCODEMPEG2_HW_DDI::SubmitFrame(MPEG2EncoderHW::EncodeFrameTask*, unsigned char*, unsigned int, unsigned char) (mfx_mpeg2_encode_full_hw.h:159)
==3316==    by 0xC36BC2E: MPEG2EncoderHW::FullEncode::SubmitFrame(sExtTask2*) (mfx_mpeg2_encode_full_hw.cpp:477)
==3316==    by 0xC36BF7E: TaskRoutineSubmit(void*, void*, unsigned int, unsigned int) (mfx_mpeg2_encode_full_hw.cpp:544)
==3316==    by 0xC0A65CA: mfxSchedulerCore::call_pRoutine(MFX_CALL_INFO&) (mfx_scheduler_core.h:531)
```
media driver is 8fb92cdaa1476f1601ba94a785e84ef313f2c0c2

**Comment by Alexandr-Konovalov** [comment]
Not reproduced with 232c32f6cbb.
